---
bibliography: ["bib/references.bib", "bib/packages.bib"]
---

# Simulation study {#sec-sim}

In this section we inspect the results from a few simulations studies. At first we study if the implemntation work. After that we study the posterior results from BBVI compared to MCMC for a simple Bayesian regression model. Finally we will compare BBVI with MCMC for a location-scale regresion model in terms of the approximation measured by the KL-divergence.

To evaluate if and how well a statistical method works, one can often not rely on analytic results about the method at hand. Instead, one can assess statistical properties or behaviours of the method by conducting simulation studies, which cover certain application scenarios by combining and modifying specific aspects regarding either the data or the method itself (Morris et al. 2019, pp. 2074-2075). This chapter describes the design of our simulation study and presents the results afterwards. The code and the raw results of the simulation study are all stored in the repository of the package in the directory /simulations.

## Study design {#sec-sd

For the design of the simulation study we follow the suggestions made by Morris et al. (ibid.). In their article, they present a guideline for planning simulations called “ADEMP”, which is an acronym for Aims, Data-generating mechanisms, Estimands and other targets, Methods, and Performance measures (ibid., pp. 2077 - 2081).}

### Study 1

### Study 2 

### Study 3

### Study 4

