---
bibliography: ["bib/references.bib", "bib/packages.bib"]
---

# Conclusion {#sec-concl}

This thesis explored variational inference for the class of Bayesian semiparametric distributional regression models. Specifically, it made use of "black box" variational inference (BBVI) for this model class and proposed an implementation in a Python [@python3] software package. In the course of several simulation studies various aspects of BBVI were examined, including accuracy and runtime. On top of that, we compared these aspects with Markov chain Monte Carlo (MCMC). One simulation study considered the consistency of BBVI's posterior means when using increasing sample sizes. We found that the posterior means exhibit behaviour of consistency, nevertheless showing significant small biases on certain occasions, even at larger sample sizes. This suggests the need for further investigation. Compared to MCMC, discrepancies emerged, notably in a normal regression model with low sample sizes where BBVI showed considerable and significant bias in estimating coefficients. Surprisingly, in a logistic regression model, BBVI sometimes outperformed MCMC in terms of bias and EmpSE. Yet, BBVI showed slower and less consistent convergence as sample sizes increased. Afterwards, an empirical approach was presented to quantify the discrepancy of the posterior distributions between BBVI and MCMC. Using this approach we observed broadly similar posterior distributions for the parameter blocks of the considered model, albeit with larger Wasserstein distances for some parameter blocks. It was also demonstrated that BBVI significantly improved runtime compared to a conventional implementation of MCMC. We conclude from our studies, that employing VI is generally not recommended for small datasets combined with low-dimensional parameter models. For these instances MCMC offers more accurate inference. In our simulation studies, a sample size of 500 appeared to be a reliable threshold for the safe application of BBVI. This finding corresponds with the advice provided by @Blei2017. Hence, one should consider resorting to VI in semiparameteric distributional regression when (a) the dataset is sufficiently large and (b) the model is sufficiently complex.

Our implementation could certainly be enhanced in multiple ways. We could improve code quality by incorporating unit and integration tests. Additionally, further testing to ensure fast runtime, robustness and compatibility with various response distributions when utilizing BBVI would be beneficial. Expanding the support for various effects within the linear predictors is another possibility for improvement. This includes accomodation of interactions between smooth effects and covariates, corresponding to varying coefficient models (VCM). Moreover, augmenting the program to handle approximations of two dimensional smooth surface functions, geoadditive effects [@Lang2004, p. 188 ff.] or latent parameters (random-effects) would be advantageous. For latent parameters, an investigation into amortized VI, a technique commonly employed in variational autoencoders (VAEs) [@Kingma2013; @Rezende2014], would be valuable. 

Studying more versatile variational families $Q$ in semiparameteric distributional regression models is interesting too. This could involve investigating approximations for discrete parameters and those confined to specific intervals, in a first step. Likewise, exploration of more flexible distributions for the factors in the variational distributions is intersting. 
Normalizing flows are here an exciting new development [@Rezende2014]. Finally, including dependencies between parameter blocks like in structured VI [@Hoffman2014], could improve the accuracy of BBVI.

Future research endeavors should also focus on conducting further empirical investigations or deriving theoretical results to understand the accuracy of certain variational approximations. This would aid in determining the most effective variational distributions for specific models and tasks. Additionally, there is a need to develop user-friendly software that enables applied researchers to employ VI for empirical studies effortlessly. These points highlight several untapped research possibilities within the fascinating field of VI.